language: python

sudo: enabled
dist: trusty

python:
  - 3.4
  - 3.5
  - 3.6

script: make test

jobs:
  include:

    - stage: Debian
      install: >
        sudo apt-get install -yq --no-install-suggests --no-install-recommends
        devscripts fakeroot equivs git-buildpackage &&
        mk-build-deps -i -s sudo -t 'apt-get -yq' debian/control
      before_script: |
        git clean -df
        git reset --hard
      script: >
        DEB_BUILD_OPTIONS=nocheck make deb &&
        sudo dpkg -i ../*.deb
      python: 3.4
      virtualenv:
        system_site_packages: true

notifications:
  email: false
